/**
 * Generates lib/ukGrid.ts: a dot grid of the United Kingdom (land = "#").
 * Run with `node scripts/build-uk-grid.mjs [rows]` — only needed if you want
 * a different resolution. Uses a simple equirectangular projection scaled by
 * cos(latitude), which the client mirrors in `projectToGrid`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { geoContains } from "d3-geo";
import { feature } from "topojson-client";

const ROWS = Number(process.argv[2] ?? 96);
const LAT_MAX = 60.9;
const LAT_MIN = 49.85;
const LON_MIN = -8.2;
const LON_MAX = 1.8;
const LAT0 = 55;

const topo = JSON.parse(readFileSync(new URL("../node_modules/world-atlas/countries-10m.json", import.meta.url)));
const uk = feature(topo, topo.objects.countries.geometries.find((g) => g.id === "826"));

const cellDeg = (LAT_MAX - LAT_MIN) / ROWS;
const lonScale = Math.cos((LAT0 * Math.PI) / 180);
const cols = Math.round(((LON_MAX - LON_MIN) * lonScale) / cellDeg);
const lonPerCell = cellDeg / lonScale;

// A cell is land if at least two of five sample points (centre + quarters) are.
const offsets = [[0.5, 0.5], [0.25, 0.25], [0.75, 0.25], [0.25, 0.75], [0.75, 0.75]];
const rows = [];
for (let y = 0; y < ROWS; y++) {
  let line = "";
  for (let x = 0; x < cols; x++) {
    let hits = 0;
    for (const [ox, oy] of offsets) {
      const lon = LON_MIN + (x + ox) * lonPerCell;
      const lat = LAT_MAX - (y + oy) * cellDeg;
      if (geoContains(uk, [lon, lat])) hits++;
    }
    line += hits >= 2 ? "#" : ".";
  }
  rows.push(line);
}

const out = `// Generated by scripts/build-uk-grid.mjs — do not edit by hand.
// United Kingdom land cells ("#") on a ${cols} × ${ROWS} grid.

export const ukGrid = {
  cols: ${cols},
  rows: ${ROWS},
  latMax: ${LAT_MAX},
  lonMin: ${LON_MIN},
  cellDeg: ${cellDeg},
  lonPerCell: ${lonPerCell},
  data: [
${rows.map((r) => `    "${r}",`).join("\n")}
  ],
} as const;

/** Maps a latitude/longitude to fractional grid coordinates. */
export function projectToGrid(lat: number, lon: number) {
  return {
    x: (lon - ukGrid.lonMin) / ukGrid.lonPerCell,
    y: (ukGrid.latMax - lat) / ukGrid.cellDeg,
  };
}
`;
writeFileSync(new URL("../lib/ukGrid.ts", import.meta.url), out);
console.log(`lib/ukGrid.ts: ${cols} × ${ROWS}, ${rows.join("").split("#").length - 1} land cells`);
